### ISSUE TITLE
Express business processes using BPMN

### ISSUE THREAD

**Issue by vityaman** [vityaman-edu/lms#3]
## Description

We need to develop some bpmn diagrams according to our task.

**Comment by vityaman** [comment]
Need to come up with tools to develop this diagrams. Maybe bpmn.io or some mermaid-like tool is capable of it.

https://bpmn.io

**Comment by vityaman** [comment]
Be aware of task statement: https://se.ifmo.ru/courses/bl

**Comment by lulalend** [comment]
first version BPMN

![LMS](https://github.com/vityaman-edu/lms/assets/80539642/f6f1dbc1-8b5d-418d-b5ff-210ad92b1dfc)

https://lucid.app/lucidchart/dee5015c-dd3a-4e98-9566-d3b13ebfac36/edit?invitationId=inv_ade19f34-b1df-4eea-9cb7-d8b0873ea84e&page=0_0#

**Comment by vityaman** [comment]
@Kimiega said:

1. Add AND operator at Homework Form.
2. Add manual handling "Сделать ДЗ".
3. Notification Message Start Event, mark end event "Send Review" as end, and start event "Send review" as start.

Also he recommended a video about bpmn: https://youtu.be/uEbQTCqyNpc?feature=shared

**Comment by vityaman** [comment]
@lulalend, looks good, but the term `homework` is so abstract here. It is not clear what are homework materials: `pdf`, `image`, `txt`, source code, test or so on. Are we going to support only sending homework with materials? I have an idea to integrate it with the `GitLab`, `GitHub` or `Codeforces`, because without it the system is just useless.

As I'm going to move this diagram to bpmn.io, you can leave it to me to fix above proposals and add additional features/integrations. It would be more useful if you just generate some ideas, leave them here and I will catch them and add to design.

**Comment by Kimiega** [comment]
> @Kimiega said:
> 
> 1. Add AND operator at Homework Form.
> 2. Add manual handling "Сделать ДЗ".
> 3. Notification Message Start Event, mark end event "Send Review" as end, and start event "Send review" as start.
> 
> Also he recommended a video about bpmn: https://youtu.be/uEbQTCqyNpc?feature=shared

Also, I think it'll be better to split in two different pools - teacher and student

**Comment by lulalend** [comment]
@Kimiega a pool is an organization, and the teacher and the student are in the same organization 
so.. I think it was right :)

**Comment by vityaman** [comment]
[Defended version of BPMN](https://modeler.cloud.camunda.io/share/e0d27464-1b57-46fb-badb-e5c762612dbe)

**Comment by vityaman** [comment]
Before closing this issue I will merge xml BPMN file.
